### ISSUE TITLE
Little comment problem in arduino_mega.ino

### ISSUE THREAD

**Issue by bigjohnson** [tibal/agipibi#1]
There is a little problem between lines 36 an 37 that break compilation

#define SRQ 2 /* GPIB 10 : Service Request
This Arduino pin must have interrupt */

should be

#define SRQ 2 /* GPIB 10 : Service Request \
This Arduino pin must have interrupt */

the end of line must be backslashed.
Thanks.

Alberto

**Comment by tibal** [comment]
Thanks a lot. Strange thing, it used to compile on older versions of Arduino IDE.
It's been so long, shame on me, thanks again.
